### PR TITLE
Added folia support

### PR DESCRIPTION
**Pull request by F3F5**
Tested

### CODE REVIEW

**Comment by nickuc** [comment]
Thank you very much for the PR!

**Comment by nickuc** [comment]
> @nickuc what's wrong with version By: [www.nickuc.com](http://www.nickuc.com) / github.com/nickuc/OpeNLogin - V ${pluginVersion} A new version of OpeNLogin is available (v${pluginVersion} -> v1.6.6).

Solved in dce4f4605e6d1d4411ae1e38dea2191cfb8a1002, thanks for reporting

**Comment by F3F5** [comment]
we have a problem 

```[02:10:38] [Folia Async Scheduler Thread #5/WARN]: java.lang.UnsupportedOperationException
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535)
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235)
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211)
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175)
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:144)
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.scheduler.BukkitRunnable.runTask(BukkitRunnable.java:45)
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at OpenLogin.jar//com.nickuc.openlogin.bukkit.command.executors.OpenLoginCommand.perform(OpenLoginCommand.java:145)
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at OpenLogin.jar//com.nickuc.openlogin.bukkit.command.BukkitAbstractCommand.lambda$onCommand$0(BukkitAbstractCommand.java:73)
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at OpenLogin.jar//com.nickuc.openlogin.lib.folialib.impl.FoliaImplementation.lambda$runAsync$1(FoliaImplementation.java:60)
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217)
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[02:10:38] [Folia Async Scheduler Thread #5/INFO]: [OpeNLogin] Failed to perform the command 'openlogin', sender: VortexL

**Comment by F3F5** [comment]
@nickuc

**Comment by nickuc** [comment]
> we have a problem
> 
> ```
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535)
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235)
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211)
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175)
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:144)
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.scheduler.BukkitRunnable.runTask(BukkitRunnable.java:45)
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at OpenLogin.jar//com.nickuc.openlogin.bukkit.command.executors.OpenLoginCommand.perform(OpenLoginCommand.java:145)
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at OpenLogin.jar//com.nickuc.openlogin.bukkit.command.BukkitAbstractCommand.lambda$onCommand$0(BukkitAbstractCommand.java:73)
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at OpenLogin.jar//com.nickuc.openlogin.lib.folialib.impl.FoliaImplementation.lambda$runAsync$1(FoliaImplementation.java:60)
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217)
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
> [02:10:38] [Folia Async Scheduler Thread #5/INFO]: [OpeNLogin] Failed to perform the command 'openlogin', sender: VortexL
> ```

This PR did not include all tasks. Fixed in dade9732ff91157ca92f96fe7256980b2e935656

**Comment by F3F5** [comment]
ah yes.. fixed

**Comment by F3F5** [comment]
You can make a release, i didn't find any problems

> > we have a problem
> > ```
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535)
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235)
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211)
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175)
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:144)
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at org.bukkit.scheduler.BukkitRunnable.runTask(BukkitRunnable.java:45)
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at OpenLogin.jar//com.nickuc.openlogin.bukkit.command.executors.OpenLoginCommand.perform(OpenLoginCommand.java:145)
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at OpenLogin.jar//com.nickuc.openlogin.bukkit.command.BukkitAbstractCommand.lambda$onCommand$0(BukkitAbstractCommand.java:73)
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at OpenLogin.jar//com.nickuc.openlogin.lib.folialib.impl.FoliaImplementation.lambda$runAsync$1(FoliaImplementation.java:60)
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217)
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> > [02:10:38] [Folia Async Scheduler Thread #5/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
> > [02:10:38] [Folia Async Scheduler Thread #5/INFO]: [OpeNLogin] Failed to perform the command 'openlogin', sender: VortexL
> > ```
> 
> This PR did not include all tasks. Fixed in [dade973](https://github.com/nickuc/OpeNLogin/commit/dade9732ff91157ca92f96fe7256980b2e935656)

**Pull request merged**
